const router = require ( 'express' ).Router()
const axios = require ( 'axios' )
const toImageKit = require ( '../middlewares/imageKit' )
const multer = require ( 'multer' )
const upload = multer()

const userController = require ( '../controllers/userController' )
const newsController = require ( '../controllers/newsController' )
const eventController = require ( '../controllers/eventController' )
const suggestController = require ( '../controllers/suggestController' )
const authentication = require ( '../middlewares/authentication' )

router.post ( '/login', userController.login )
router.get ( '/news', newsController.read )
router.get ( '/news/:id', newsController.findOne )
router.get ( '/events', eventController.read )
router.get ( '/events/:id', eventController.findOne )
router.post ( '/suggest', suggestController.create )

router.use ( authentication )
router.post ( '/news', upload.single('galeri'), toImageKit, newsController.create )
router.patch ( '/news/:id/editTitle', newsController.modifyTitle )
router.patch ( '/news/:id/editImage', upload.single('galeri'), toImageKit, newsController.modifyImage )
router.patch ( '/news/:id/editDescription', newsController.modifyDescription )
router.patch ( '/news/:id/editDate', newsController.modifyDate )
router.delete ( '/news/:id', newsController.delete )
router.post ( '/events', upload.single('galeri'), toImageKit, eventController.create )
router.patch ( '/events/:id/editTitle', eventController.modifyTitle )
router.patch ( '/events/:id/editImage', upload.single('galeri'), toImageKit, eventController.modifyImage )
router.patch ( '/events/:id/editDescription', eventController.modifyDescription )
router.patch ( '/events/:id/editDate', eventController.modifyDate )
router.delete ( '/events/:id', eventController.delete )
router.get ( '/suggest', suggestController.read )
router.delete ( '/suggest/:id', suggestController.delete )

module.exports = router